version: '2'
services:
  buildbot:
    image: bobdrummond/buildbot_docker_master:v1.0.0
    build:
      context: ./master
    env_file:
        - db.env
    environment:
      - BUILDBOT_MASTER_FQDN=10.0.0.9
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8080/
      - BUILDBOT_WEB_PORT=8080
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9989:9989"
  db:
    env_file:
        - db.env
    image: "postgres:9.4"
    expose:
        - 5432
