version: '2'
services:
  buildbot:
    image: bobdrummond/buildbot_docker_master
    build:
      context: ./master
    env_file:
        - buildbot.env
    volumes:
      - ./master.cfg:/var/lib/buildbot/master.cfg:ro
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9989:9989"
  db:
    env_file:
        - buildbot.env
    image: "postgres:9.4"
    expose:
        - 5432
